<?php

declare(strict_types=1);

use GraystackIT\MollieBilling\Enums\PlanChangeMode;
use GraystackIT\MollieBilling\Enums\SubscriptionStatus;

return [
    'billable_model' => env('BILLING_BILLABLE_MODEL'),

    'logo_url' => env('BILLING_LOGO_URL'),
    'favicon_url' => env('BILLING_FAVICON_URL'),
    'primary_color' => env('BILLING_PRIMARY_COLOR', 'teal'),
    'company_name' => env('APP_NAME'),

    // URL the portal logo links to (e.g. main app dashboard). When null the logo
    // links to the billing dashboard itself. Supports a plain URL string or a named
    // route via the 'route:' prefix, e.g. 'route:dashboard'.
    'dashboard_url' => env('BILLING_DASHBOARD_URL'),

    // Where the checkout "Back" link leads when no explicit $backUrl is passed.
    'checkout_back_url' => env('BILLING_CHECKOUT_BACK_URL', '/'),

    // Countries available in the checkout country selector.
    // 'regions': built-in groups — currently only 'EU' (27 member states).
    // 'include': additional ISO-3166-1 alpha-2 codes (e.g. ['CH', 'GB']).
    // 'exclude': codes to remove from the resolved list.
    // Countries from 'additional_countries' below are also included automatically.
    'checkout_countries' => [
        'regions' => ['EU'],
        'include' => [],
        'exclude' => [],
    ],

    // Default country pre-selected in the checkout/billing-data dropdown when no
    // billable country is persisted yet and the IP-based lookup yields no result.
    'default_billing_country' => env('BILLING_DEFAULT_COUNTRY', 'AT'),

    'redirect_after_return' => env('BILLING_REDIRECT_AFTER_RETURN'),

    'require_payment_method_for_zero_amount' => env('BILLING_REQUIRE_PM_ZERO', true),

    // Package-wide currency (ISO-4217). Prices in mollie-billing-plans.php and coupon amounts
    // are interpreted in this currency. Mollie payments, sales invoices and BillingInvoice
    // persist this code. The EU VAT/OSS system (mpociot/vat-calculator, VIES, OSS export)
    // is EU-only but the currency itself is independent of it.
    'currency' => env('BILLING_CURRENCY', 'EUR'),
    'currency_symbol' => env('BILLING_CURRENCY_SYMBOL', '€'),

    // Invoice PDF generation and storage. PDFs are generated locally via elegantly/laravel-invoices
    // and stored on the configured Laravel filesystem disk.
    'invoices' => [
        // Laravel filesystem disk for storing generated PDF invoices.
        'disk' => env('BILLING_INVOICE_DISK', 'local'),

        // Base path within the disk. Invoices are stored as {path}/{YYYY/MM}/{serial}.pdf.
        'path' => 'billing/invoices',

        // Logo image displayed in the top-right corner of invoices.
        // Supported formats:
        //   - APP_URL-based URL: "${APP_URL}/logo.png" (resolved to public_path)
        //   - Relative path:    "images/logo.png"      (resolved to public_path)
        //   - Absolute path:    "/var/www/public/logo.png"
        //   - Data URI:         "data:image/png;base64,..."
        'logo' => env('BILLING_INVOICE_LOGO'),

        // Seller information printed on every invoice.
        'seller' => [
            'company' => env('BILLING_SELLER_COMPANY'),
            'name' => env('BILLING_SELLER_NAME'),
            'email' => env('BILLING_SELLER_EMAIL'),
            'phone' => env('BILLING_SELLER_PHONE'),
            'tax_number' => env('BILLING_SELLER_TAX_NUMBER'),
            'address' => [
                'street' => env('BILLING_SELLER_STREET'),
                'city' => env('BILLING_SELLER_CITY'),
                'postal_code' => env('BILLING_SELLER_POSTAL_CODE'),
                'state' => env('BILLING_SELLER_STATE'),
                'country' => env('BILLING_SELLER_COUNTRY'),
            ],
        ],

        // Serial number format. P=prefix, Y=year, C=counter (each char = one digit slot).
        'serial_number' => [
            'format' => 'PP-YYCCCCCC',
            'prefix' => [
                'invoice' => 'IN',
                'credit_note' => 'CR',
                'one_time_order' => 'OT',
            ],
        ],

        // Temporary URL expiry in minutes (for S3-compatible disks).
        'temporary_url_expiry' => 30,
    ],

    // OSS (One-Stop Shop) export storage. CSVs are generated by a queued job
    // and stored on the configured Laravel filesystem disk so the admin portal
    // can hand out a short-lived download URL — works with S3-compatible
    // private buckets via temporaryUrl().
    'oss' => [
        // Disk for storing OSS export CSVs. Falls back to invoices.disk when null.
        'disk' => env('BILLING_OSS_DISK'),

        // Base path within the disk. Files are stored as {path}/oss-export-{YYYY}-{timestamp}.csv.
        'path' => env('BILLING_OSS_PATH', 'billing/oss-exports'),

        // Temporary URL expiry in minutes (for S3-compatible disks).
        'temporary_url_expiry' => 30,
    ],

    // Default for Billable::allowsBillingOverage() — overridable per billable.
    'allow_overage_default' => env('BILLING_ALLOW_OVERAGE', true),

    // Controls how plan changes are applied:
    // Immediate    — always applied immediately (with prorata billing)
    // EndOfPeriod  — always scheduled for the end of the current period
    // UserChoice   — the user decides (both options shown in the portal)
    'plan_change_mode' => PlanChangeMode::from(
        env('BILLING_PLAN_CHANGE_MODE', PlanChangeMode::UserChoice->value)
    ),

    'mollie_locale' => env('BILLING_MOLLIE_LOCALE'),

    // Primary key type of the billable model — set before first migration run.
    'billable_key_type' => env('BILLING_BILLABLE_KEY_TYPE', 'uuid'), // uuid|ulid|int

    // Primary key type of the auth user model (used e.g. for resolved_by_user_id
    // on country mismatches). Set before first migration run.
    'user_key_type' => env('BILLING_USER_KEY_TYPE', 'int'), // uuid|ulid|int

    'ip_geolocation' => [
        'driver' => env('BILLING_IP_DRIVER', 'ipinfo_lite'),
        'drivers' => [
            'ipinfo_lite' => ['token' => env('IPINFO_TOKEN')],
            'db_ip' => ['api_key' => env('DB_IP_API_KEY')],
            'null' => [],
        ],
    ],

    // IP-based country gating. Applied to every package route except the Mollie
    // webhook (we don't know where webhooks come from). When a request resolves
    // to a country that is not allowed, the user is sent to a static "blocked"
    // page that explains why and links back to "/".
    //
    //   mode = 'blocklist' → 'countries' lists the COUNTRIES TO BLOCK; everything else passes.
    //   mode = 'allowlist' → 'countries' lists the ONLY COUNTRIES ALLOWED; everything else is blocked.
    //
    // 'block_unknown' decides what happens when the geolocation lookup yields
    // no country (private IP, lookup error, driver returned null). Default is
    // false — unknowns pass through. Set to true for strict allowlist setups.
    //
    // 'countries' can be configured via the BILLING_IP_BLOCK_COUNTRIES env
    // variable as a comma-separated list of ISO-3166-1 alpha-2 codes
    // (e.g. "RU,KP,IR"). Whitespace is trimmed and codes are upper-cased. When
    // set, the env value takes precedence over any inline array below.
    'ip_block' => [
        'enabled' => env('BILLING_IP_BLOCK_ENABLED', false),
        'mode' => env('BILLING_IP_BLOCK_MODE', 'blocklist'),
        'countries' => array_values(array_filter(array_map(
            fn (string $iso): string => strtoupper(trim($iso)),
            explode(',', (string) env('BILLING_IP_BLOCK_COUNTRIES', ''))
        ))),
        'block_unknown' => env('BILLING_IP_BLOCK_UNKNOWN', false),
    ],

    'overage_job_time' => env('BILLING_OVERAGE_JOB_TIME', '02:00'),

    // Daily run-time for ProcessTrialLifecycleJob (UTC). The job sends
    // trial-ending notifications and expires trials whose `trial_ends_at`
    // has passed without a successful first charge. Scheduled separately
    // from the overage job so trial-lifecycle bookkeeping stays decoupled.
    'trial_lifecycle_job_time' => env('BILLING_TRIAL_LIFECYCLE_JOB_TIME', '02:05'),

    // Cleanup of orphaned billables — billables that were created during a
    // checkout flow but never reached an active subscription (user closed the
    // tab, Mollie webhook never arrived, mandate was set up but the first
    // payment was abandoned, …). The CleanupOrphanedBillablesJob runs every
    // 15 minutes by default and deletes such records once they exceed
    // `threshold_minutes` of age.
    //
    // Detection (hybrid):
    //   - If the billable has a `pending_first_payment_id` in subscription_meta,
    //     Mollie is polled and the record is only cleaned when the payment is
    //     in a terminal failure state (failed/canceled/expired).
    //   - Otherwise the billable is cleaned purely based on age + the absence
    //     of an accessible subscription.
    //
    // The actual deletion is delegated to MollieBilling::cleanupOrphanedBillableUsing()
    // when an app registers a closure (e.g. to also delete the related User /
    // tenant record). When no closure is registered the package soft-deletes
    // the billable directly via `$billable->delete()`.
    'cleanup' => [
        'enabled' => env('BILLING_CLEANUP_ORPHANED_ENABLED', true),
        'threshold_minutes' => (int) env('BILLING_CLEANUP_ORPHANED_THRESHOLD_MINUTES', 60),
        'cron_expression' => env('BILLING_CLEANUP_ORPHANED_CRON', '*/15 * * * *'),
    ],

    'usage_threshold_percent' => env('BILLING_USAGE_THRESHOLD', 80),

    // Whether unused usage credits carry over to the next billing period.
    // When false, wallets are reset to the plan's included quota on each renewal.
    // Can be overridden per plan in mollie-billing-plans.php.
    'usage_rollover' => env('BILLING_USAGE_ROLLOVER', false),

    // Admin KPI cache TTL in seconds
    'admin_kpi_cache_ttl' => env('BILLING_ADMIN_KPI_TTL', 300),

    'show_yearly_savings' => env('BILLING_SHOW_YEARLY_SAVINGS', true),

    // Behavior of free / Local subscriptions (subscription_source = local).
    //
    // Local subs have no Mollie mandate, so paid extras (add-ons, extra seats)
    // can never be charged and are always blocked. One-time product purchases,
    // however, are oneoff card payments and Mollie accepts them without a
    // mandate — whether that fits your business model is up to you.
    //
    //   true  → free-plan users can purchase one-time products (token packs etc.)
    //   false → purchase attempts throw LocalSubscriptionCannotPurchaseProductsException
    //           and the products page hides the buy buttons with an upgrade hint.
    'local_subscription' => [
        'allow_one_time_orders' => env('BILLING_LOCAL_ALLOW_ONE_TIME_ORDERS', false),
    ],

    'vat_rate_overrides' => [
        // 'DE' => 19.0,
    ],

    'additional_countries' => [
        // 'CH' => ['vat_rate' => 8.1, 'name' => 'Switzerland'],
    ],

    // Queue connection and name used for all background jobs and queued
    // notifications dispatched by this package (PrepareUsageOverageJob,
    // RetryUsageOverageChargeJob, RevokeMollieMandateJob, …).
    // null on either key falls back to the framework default
    // (queue.default connection / "default" queue name).
    'queue' => [
        'connection' => env('BILLING_QUEUE_CONNECTION'),
        'name' => env('BILLING_QUEUE_NAME'),
    ],

    // IANA timezone for displaying billing dates in the portal as the fallback
    // when a billable does not override Billable::getBillingTimezone(). Persistence
    // and computation are always in UTC; admin views also render in UTC for
    // forensic parity with the database. See docs/timezone.md.
    'billing_timezone' => env('BILLING_TIMEZONE', 'UTC'),
];
